version: '3.8'

services:

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
      - OPENWEATHERMAP_API_KEY=aa932aa2a7b8bea650af8afec692e67e
      - WEATHERBIT_API_KEY=9988561577c3409693161c0cf240ca6d
      - TZ=Europe/Moscow 
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
